name: Django CD

on:
  pull_request:
    types:
      - closed
    branches: [ develop ]

jobs:
  cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.10.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./django_back/requirements.txt

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setting .env
        run: |
          echo "${{ secrets.DJANGO_BACK_ENV_FILE }}" >> .env
          cat .env

      - name: Create db env file
        run: |
          echo "${{ secrets.DB_ENV_FILE }}" > ./db/.env

      - name: Build docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker images

      - name: Push docker images
        run: docker-compose -f docker-compose.yml push

      - name: Connect to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY_PEM }}
          port: ${{ secrets.PORT }}
          script: |
            cd backend
            git pull
            sudo docker-compose -f docker-compose.yml down
            sudo docker-compose -f docker-compose.yml pull
            sudo docker-compose -f docker-compose.yml up -d --build
